export enum NotificationIdentifier {
  REACTED_TO_POST = 'REACTED_TO_POST',
  REACTED_TO_COMMUNITY_POST = 'REACTED_TO_COMMUNITY_POST',
  comment_notification = 'comment-notification',
  COMMUNITY_COMMENT = 'COMMUNITY_COMMENT',
  COMMENT = 'COMMENT',
  group_invite_notifications = 'group-invite-notifications',
  send_notification = 'send-notification',
  like_notification = 'like-notification',
  community_post_like_notification = 'community-post-like-notification',
  community_post_comment_notification = 'community-post-comment-notification',
  follow_user = 'follow-user',
  un_follow_user = 'un-follow-user',
  official_group_request = 'official-group-request',
  reject_official_group_request = 'reject-official-group-request',
  accept_official_group_request = 'accept-official-group-request',
  reject_private_join_group_request = 'reject-private-join-group-request-group-request',
  accept_private_join_group_request = 'accept-private-join-group-request-group-request',
  delete_community_group = 'delete-community-group',

  community_post_live_request_notification = 'community_post_live_request_notification',
  community_post_rejected_notification = 'community_post_rejected_notification',
  community_post_accepted_notification = 'community_post_accepted_notification',
}
