# name: Build and Deploy to EC2

# on:
#   push:
#     branches:
#       - dev

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Build Docker Image
#         run: docker build -t unibuzz-api:latest .

#       - name: Save Docker Image to Tar
#         run: docker save unibuzz-api:latest -o unibuzz-api.tar

#       - name: Copy Image and .env to EC2
#         uses: appleboy/scp-action@v0.1.4
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.EC2_SSH_KEY }}
#           source: |
#             unibuzz-api.tar
#             .env
#           target: /home/ec2-user/

#       - name: SSH and Run Docker on EC2
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.EC2_SSH_KEY }}
#           script: |
#             docker load -i unibuzz-api.tar
#             docker stop unibuzz-api || true
#             docker rm unibuzz-api || true
#             docker run -d \
#               --name unibuzz-api \
#               --env-file /home/ec2-user/.env \
#               -p 3000:3000 \
#               unibuzz-api:latest
